package ru.zinin.frigate.analyzer.telegram.bot.handler.export

import io.github.oshai.kotlinlogging.KotlinLogging
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Job
import kotlinx.coroutines.launch
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty
import org.springframework.stereotype.Component
import ru.zinin.frigate.analyzer.telegram.service.model.CancellableJob
import ru.zinin.frigate.analyzer.telegram.service.model.ExportMode
import java.util.UUID
import java.util.concurrent.ConcurrentHashMap

private val logger = KotlinLogging.logger {}

/**
 * In-memory registry of currently active video exports.
 *
 * Primary key is a synthetic `exportId` (UUID) generated by the caller. Secondary dedup indexes:
 * - `byRecordingId` — guards QuickExport duplicates per recording.
 * - `byChat` — guards /export duplicates per chat.
 *
 * Namespaces are independent: a QuickExport for some recording does not block a /export in the
 * same chat.
 */
@Component
@ConditionalOnProperty(prefix = "application.telegram", name = ["enabled"], havingValue = "true")
class ActiveExportRegistry(
    private val exportScope: ExportCoroutineScope,
) {
    enum class State { ACTIVE, CANCELLING }

    // Plain `class` (not `data class`): Entry holds `var`s (`cancellable`, `state`) whose values
    // mutate concurrently. A data class's synthesized equals/hashCode over mutable state is a
    // latent footgun — Entry is identified by `exportId` alone, and this registry already keys
    // maps on the UUID rather than on Entry instances.
    class Entry(
        val exportId: UUID,
        val chatId: Long,
        val mode: ExportMode,
        val recordingId: UUID?,
        val job: Job,
        @Volatile var cancellable: CancellableJob? = null,
        @Volatile var state: State = State.ACTIVE,
    )

    sealed class StartResult {
        data class Success(
            val exportId: UUID,
        ) : StartResult()

        data object DuplicateRecording : StartResult()

        data object DuplicateChat : StartResult()
    }

    private val byExportId = ConcurrentHashMap<UUID, Entry>()
    private val byRecordingId = ConcurrentHashMap<UUID, UUID>()
    private val byChat = ConcurrentHashMap<Long, UUID>()
    private val startLock = Any()

    fun tryStartQuickExport(
        exportId: UUID,
        chatId: Long,
        mode: ExportMode,
        recordingId: UUID,
        job: Job,
    ): StartResult =
        synchronized(startLock) {
            // Atomic under startLock: putIfAbsent(byRecordingId) + byExportId[...] = Entry so that
            // a failure between the two doesn't leave byRecordingId permanently locked.
            // NOTE: startLock also linearizes two concurrent starts racing to self-heal the same
            // stale secondary — do not remove on the assumption that CHM alone is enough.
            val existing = byRecordingId.putIfAbsent(recordingId, exportId)
            if (existing != null) {
                // Self-heal: release() removes byExportId BEFORE cleaning secondary indexes, so a
                // concurrent release can leave byRecordingId pointing at an already-gone entry.
                // If the primary index no longer contains `existing`, the stale secondary entry is
                // our leftover — replace it and proceed.
                if (byExportId.containsKey(existing)) return StartResult.DuplicateRecording
                byRecordingId[recordingId] = exportId
            }
            byExportId[exportId] = Entry(exportId, chatId, mode, recordingId, job)
            return StartResult.Success(exportId)
        }

    fun tryStartDialogExport(
        exportId: UUID,
        chatId: Long,
        mode: ExportMode,
        job: Job,
    ): StartResult =
        synchronized(startLock) {
            val existing = byChat.putIfAbsent(chatId, exportId)
            if (existing != null) {
                // Self-heal same race as tryStartQuickExport — see comment above.
                if (byExportId.containsKey(existing)) return StartResult.DuplicateChat
                byChat[chatId] = exportId
            }
            byExportId[exportId] = Entry(exportId, chatId, mode, null, job)
            return StartResult.Success(exportId)
        }

    /**
     * Publishes the cancel handle. If the entry is already `CANCELLING` at the time of publication
     * (because a cancel click arrived between `submitWithRetry` and this call), fire-and-forget the
     * cancel so the vision server is still told to stop.
     */
    fun attachCancellable(
        exportId: UUID,
        cancellable: CancellableJob,
    ) {
        val entry = byExportId[exportId] ?: return
        // DO NOT REORDER: cancellable must be published (line below) before the state check.
        // If the check came first and found ACTIVE, a concurrent markCancelling + CancelHandler
        // read of entry.cancellable could observe null because the write wasn't flushed yet.
        // With cancellable written first, the reader either sees the new cancellable (via @Volatile
        // happens-before) or the cancellable arrived too late and this method's state check
        // itself triggers the fire-and-forget cancel on line below.
        entry.cancellable = cancellable
        if (entry.state == State.CANCELLING) {
            exportScope.launch {
                // Don't use runCatching — it catches Throwable including CancellationException,
                // which would break graceful shutdown propagation on exportScope cancellation.
                try {
                    cancellable.cancel()
                } catch (e: CancellationException) {
                    throw e
                } catch (e: Exception) {
                    // cancelJob itself is tolerant (409/5xx/timeout logged WARN internally), so this
                    // branch only fires on truly unexpected errors — log WARN per design §9.
                    logger.warn(e) {
                        "Vision server cancel failed on attach-retry path, exportId=$exportId"
                    }
                }
            }
        }
    }

    /**
     * Atomic transition `ACTIVE → CANCELLING` under `computeIfPresent` + `synchronized(entry)`.
     * Closes the TOCTOU race vs. `release()` — if a concurrent release removes the entry from the
     * map, `computeIfPresent` sees null and we return null cleanly.
     *
     * @return the entry snapshot after the transition on success, `null` if the entry does not
     *   exist (released) or is already in `CANCELLING`.
     */
    fun markCancelling(exportId: UUID): Entry? {
        var snapshot: Entry? = null
        byExportId.computeIfPresent(exportId) { _, entry ->
            synchronized(entry) {
                if (entry.state != State.CANCELLING) {
                    entry.state = State.CANCELLING
                    snapshot = entry
                }
            }
            entry
        }
        return snapshot
    }

    fun get(exportId: UUID): Entry? = byExportId[exportId]

    /**
     * Idempotent. Order of operations matters:
     *  1. `byExportId.remove(exportId)` — takes the CHM bucket lock briefly. Returns null on
     *     double-call (idempotent).
     *  2. Then `synchronized(entry)` only around secondary-index cleanup.
     *
     * Why this order: if we took `synchronized(entry)` FIRST and then removed from byExportId,
     * we'd acquire (entry monitor → bucket lock). Meanwhile `markCancelling` holds the bucket
     * lock inside `computeIfPresent` and tries to acquire the entry monitor. Two threads →
     * reverse lock order → **deadlock**. By removing from byExportId BEFORE taking the entry
     * monitor, a concurrent `markCancelling` sees the entry absent via `computeIfPresent` and
     * returns null cleanly.
     *
     * Called both from `finally` of the export coroutine and from `Job.invokeOnCompletion` —
     * double-call is safe.
     */
    fun release(exportId: UUID) {
        val entry = byExportId.remove(exportId) ?: return
        synchronized(entry) {
            entry.recordingId?.let { byRecordingId.remove(it, exportId) }
            byChat.remove(entry.chatId, exportId)
        }
    }

    /**
     * Test-only accessor. Returns a snapshot of the primary index. Used by tests in
     * `QuickExportHandlerTest`, `ExportExecutorTest`, and `CancelExportHandlerTest` to locate
     * the active export entry without reflection.
     *
     * `internal` keeps this out of the public API surface of the module.
     */
    internal fun snapshotForTest(): Map<UUID, Entry> = byExportId.toMap()
}
